
spring:
  datasource:
    druid:
      url: jdbc:mysql://47.98.172.169:3306/new_world?serverTimezone=GMT%2B8
      username: root
      password: 123456
  redis:
    database: 0
    host: 47.98.172.169
    timeout: 5000
    port: 6379
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    password: 123456
server:
  port: 9000

logging:
  level:
    com.suave.newworld.dao: debug

token:
  #  过期时间（秒）
  expiration: 3600
  # token秘钥
  secret: suave
  # token签发者
  iss: suave
